AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - "db/schema.rb"
  UseCache: false
Rails:
  Enabled: true
Rails/UnknownEnv:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/Documentation:
  Enabled: false
Lint/AmbiguousOperator:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Security/Eval:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Lint/Debugger:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Rails/FindEach:
  Enabled: false
Style/Next:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Layout/EmptyLinesAroundMethodBody:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Lint/UnusedBlockArgument:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/Proc:
  Enabled: false
Layout/DotPosition:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Style/Lambda:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Lint/UnderscorePrefixedVariableName:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Style/ColonMethodCall:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Style/SignalException:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Lint/UnneededSplatExpansion:
  Enabled: false
Layout/IndentHash:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Performance/StringReplacement:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/NestedTernaryOperator:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Style/Semicolon:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/NestedParenthesizedCalls:
  Enabled: false
Lint/ParenthesesAsGroupedExpression:
  Enabled: false
Layout/AlignParameters:
  Enabled: false
Performance/RedundantMerge:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/MethodMissing:
  Enabled: false
Lint/Loop:
  Enabled: false
