source 'https://rubygems.org'
ruby '2.4.4'

gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'carrierwave', '~> 1.0'
gem 'ckeditor', '4.1.3'
gem 'cloudinary'
gem 'devise'
gem 'faker', '~> 1.7'
gem 'figaro'
gem 'font-awesome-sass'
gem 'fontello_rails_converter'
gem 'friendly_id', '~> 5.1.0'
gem 'gibbon'
gem 'i18n-tasks', '~> 0.9.17'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'pg'
gem 'postmark'
gem 'puma'
gem 'pundit', '~> 1.1'
gem 'rails', '5.0.0.1'
gem 'rails-i18n', '~> 5.0.0'
gem 'rails_admin', '>= 1.0.0.rc'
gem 'raygun4ruby'
gem 'redis'
gem 'remotipart', github: 'mshibuya/remotipart'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'
gem 'validates_email_format_of'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem "letter_opener"
  gem 'listen', '~> 3.0.5'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rubocop', '~> 0.52'
end
